[workspace]
resolver = "3"
members = ["apps/*", "crates/*", "examples/*"]
default-members = ["crates/nade"]

[workspace.package]
version = "0.0.1"
edition = "2024"
license = "MIT"
authors = ["POTI <potistudio@proton.me>"]
publish = false

[profile.release]
lto = true
codegen-units = 1

[workspace.lints.clippy]
all = "warn"

[workspace.dependencies]
log = "0.4.29"
iced = { version = "0.14", features = ["advanced", "canvas"] }
anyhow = "1.0.100"
env_logger = "0.11.8"
constants = { path = "crates/constants" }
nade-engine = { path = "crates/engine" }
nade-timeline = { path = "crates/timeline_panel" }
core = { path = "crates/core" }
domain = { path = "crates/domain" }
operators = { path = "crates/operators" }
uuid = { version = "1.19.0", features = ["v4", "serde"] }
serde = { version = "1.0.228", features = ["derive"] }
