[package]
name = "panel_system"
description = "Blender-style area tiling system for Iced applications"
authors.workspace = true
version.workspace = true
license.workspace = true
publish.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
iced = { workspace = true, features = ["image"] }
