[package]
name = "desktop"
description = "Nade app (Desktop)"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
env_logger.workspace = true
iced = "0.14.0"
log.workspace = true
nade-engine.workspace = true
constants.workspace = true
