[package]
name = "nade"
description = "Built to Create. Programmed to Kill Adobe."
repository = "https://github.com/potistudio/Nade"
keywords = ["audio", "composition", "effect", "graphics", "linux", "macos", "video", "windows"]
categories = ["multimedia::video", "gui"]
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
publish.workspace = true

[lints]
workspace = true

[[bin]]
name = "nade"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
env_logger.workspace = true
log.workspace = true
image = "0.25.8"
iced = { version = "0.14", features = ["image", "debug", "tokio", "canvas"] }
status_bar = { path = "../status_bar" }
core = { path = "../core" }
panel_system = { path = "../panel_system" }
timeline_widget = { path = "../timeline" }
rayon = "1.10"
