[package]
name = "browser_panel"
description = "Browser panel"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
iced.workspace = true
uuid.workspace = true
domain.workspace = true
constants.workspace = true
core = { workspace = true }
